# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tMw2In7p9n9ZT8O-S6Hs2iKzjqssUIAD
"""

a = 3
b =6
print(a+b)

